#!/usr/bin/env node
var ArgumentParser = require('argparse').ArgumentParser;
var path = require('path');

function main(argv) {
  var parser = new ArgumentParser({
    description: 'fake adb executable for testing',
    addHelp: true
  });

  parser.addArgument(['-s', '--serial'], {
    type: 'string',
    aliases: ['serial'],
    required: false,
    help: 'device serial, synonymous to ANDROID_SERIAL'
  });

  parser.addArgument(['-H', '--host'], {
    type: 'string',
    aliases: ['host'],
    required: false,
    help: 'device attached to remote host'
  });

  parser.addArgument(['-P', '--port'], {
    type: 'int',
    aliases: ['port'],
    required: false,
    help: 'device attached to remote port'
  });

  var args = parser.parseKnownArgs(argv);
  var modulePath = path.resolve(__dirname, 'commands', args[1].shift());

  require(modulePath).apply(args[0], args[1]);
}

if (require.main === module) {
  main(process.argv.slice(2));
}
