#!/usr/bin/env node

var net = require('net');

function main() {
  var port = parseInt(process.argv[2], 10);
  net.createServer(function(connection) {
    connection.on('data', connection.write.bind(connection));
  })
  .listen(port);
}

if (require.main === module) {
  main();
}
