/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.custom", "4771dc63-0de2-4bff-a0a1-8e5325c16618");
user_pref("app.update.lastUpdateTime.user-agent-updates-timer", 0);
user_pref("browser.cache.disk.capacity", 71508);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("consoleservice.enabled", true);
user_pref("device.storage.writable.name", "sdcard");
user_pref("devtools.eventlooplag.threshold", 100);
user_pref("dom.mms.requestReadReport", false);
user_pref("dom.mms.requestStatusReport", false);
user_pref("dom.mms.retrieval_mode", "automatic-home");
user_pref("dom.mozApps.homescreenURL", "app://verticalhome.gaiamobile.org/manifest.webapp");
user_pref("dom.mozApps.maxLocalId", 1067);
user_pref("dom.mozApps.signed_apps_installable_from", "https://marketplace.firefox.com,https://marketplace.allizom.org");
user_pref("dom.mozApps.use_reviewer_certs", false);
user_pref("dom.mozApps.used", true);
user_pref("dom.sms.maxReadAheadEntries", 7);
user_pref("dom.sms.requestStatusReport", false);
user_pref("gecko.buildID", "20150331010203");
user_pref("gecko.mstone", "40.0a1");
user_pref("intl.accept_languages", "en-US, en");
user_pref("layers.effect.contrast", "0.0");
user_pref("layers.effect.grayscale", false);
user_pref("layers.effect.invert", false);
user_pref("marionette.force-local", false);
user_pref("network.debugging.enabled", false);
user_pref("network.proxy.autoconfig_url", "data:text/plain,function FindProxyForURL(url, host) { if (shExpMatch(host, 'localhost') || shExpMatch(host, '127.0.0.1')) { return 'DIRECT'; } return 'DIRECT'; }");
user_pref("network.proxy.browsing.enabled", false);
user_pref("network.proxy.browsing.host", "");
user_pref("network.proxy.browsing.port", 0);
user_pref("network.proxy.type", 2);
user_pref("privacy.donottrackheader.value", -1);
user_pref("ril.numRadioInterfaces", 2);
user_pref("ril.radio.disabled", false);
user_pref("security.turn_off_all_security_so_that_viruses_can_take_over_this_computer", true);
user_pref("toolkit.telemetry.previousBuildID", "20150331010203");
